sudo: required
services:
  - docker
  
before_install:
  - docker build -t isidaruk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true isidaruk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-eu-central-1-966278727093"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
