# Works well with docker and docker-compose CLI
# docker run -p 3000:3000 -v /home/node/app/node_modules -v $(pwd):/home/node/app
# or
# docker-compose up --build
FROM node:alpine

WORKDIR /home/node/app

COPY --chown=node:node package.json .

RUN npm install

COPY --chown=node:node . .

# At the end, set the user to use when running this image
USER node

CMD npm run start
